server:
  port: 8080

logging:
  level:
    root: warn

spring:
  application:
    name: SearchEngine

  datasource:
    url: jdbc:postgresql://localhost:5432/searchengine
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://sendel.ru
      name: SenDel.Ru
